### ISSUE TITLE
 How do you get hijri date on your Android ?

### ISSUE THREAD

**Issue by aelmahmoudy** [khalid-hussain/HisnulMuslim#2]
I noticed in the screenshots that the date on your phone is displayed in Hijri, how did you do that ?

**Comment by khalid-hussain** [comment]
It is an Xposed Module and requires the phone to be rooted. Its XDA page can be found over [here](http://forum.xda-developers.com/xposed/modules/mod-hijri-date-statusbar-t2790604).
