### ISSUE TITLE
Repackaging

### ISSUE THREAD

**Issue by ahmedre** [khalid-hussain/HisnulMuslim#30]
imho, you should keep your packaging somewhat consistent.

some thoughts:
1. let's remove 'example' from your package name - i.e. `com.khalid.hisnulmuslim`
2. make package names singular (`.adapter` instead of `.adapters`, etc).
3. rename `classes` package (contains `Dua` right now) - `classes` isn't a good name for a package.
4. move `database` and `loader` packages under `com.khalid.hisnulmuslim`

**Comment by khalid-hussain** [comment]
1. Okay.
2. Okay.
3. Do you have any suggestions?
4. Okay.

Should I move 'adapter' and 'classes' under 'com.khalid.hisnulmuslim' as well?

JazakAllahu khayran.

**Comment by ahmedre** [comment]
yes, `adapter` and whatever you rename `classes` to should go under `com.khalid.hisnulmuslim`. how about `model` since they are model objects for communicating between the database and ui?

**Comment by hussaini** [comment]
`model` sounds good to me for replacing `classes`
