### ISSUE TITLE
I want to publish this application on Google Play Store.

### ISSUE THREAD

**Issue by lovebdsobuj** [khalid-hussain/HisnulMuslim#56]
Assalamu Alaikum Wa Rahmatullahi Wa Barakatuh,

Sir,
I want to publish this application on Google Play Store.

I live in `Bangladesh`, so I want to make this application for Bangladeshis people.

**Comment by lovebdsobuj** [comment]
Sir,
I need your help, 
I want to add new Column `bn_transliteration` (Arabic pronunciation in Bangla Language)

How can I do that?

**Comment by khalid-hussain** [comment]
وعليكم السلام ورحمة الله وبركاته 

What is the issue or question?

**Comment by lovebdsobuj** [comment]
JazakAllahu Khayir, sir.
Allah give you good reward for developing such as app.

Alhamdulillah, Everything is okay. Now, I'm trying to insert new column in `hisnulislam` database that's `transliteration` (Arabic pronunciation in Bangla language). 
Hope, I'm done.
If anything wrong, then I'll contact with you back.

My first post was permission related.

**Comment by khalid-hussain** [comment]
I have deliberately left out transliteration of the Arabic. I don't believe it helps in pronunciation and can at times lead to the wrong pronunciation. Furthermore, each language or character set may have various transliteration systems in place. so how do we choose one over the other? Users still have to learn the transliteration table to be able to correctly pronounce anyway so they might as well learn the Arabic letters and its vowels.

To this end, I've tried my best to include all the vowel marks to the point of making sure the fonts included can display the vowel marks clearly in all forms of the letters and word combinations.

P.S. Jajakallahu -> JazakAllahu, the first is ج and the second is ز . Their sounds are very different. The same mistake is repeated in the next word ('jaja').

**Comment by lovebdsobuj** [comment]
Mash Allah. 
Now, I'm feeling good moment with this conversation. Alhamdulillah.
I need a good teacher to learn Arabic.
Hope one day I speak Arabic language.
Allah give me Tawfiq. (وما توفيقي الا بالله)

JazakAllahu khairan fid darayin.
