### ISSUE TITLE
Any update?

### ISSUE THREAD

**Issue by drmiaji** [khalid-hussain/HisnulMuslim#62]
Could you please update the files, dependencies and other things so that it runs smoothly with the latest Android? 

This is a very nice app. I would appreciate if you please update it to avoid
1. app crashes
2. database needs to be dropped and updated when the database is updated. 
3. clashes with the new Android builds.

Thanks in advance for the hardworking.

**Comment by khalid-hussain** [comment]
I'm working on it now. I'm thinking of dropping the database altogether and using XML but I'm not sure.

**Comment by khalid-hussain** [comment]
I've updated the repository to use AndroidX compatibility library and an upgraded Gradle along with minor changes to make it run on Android Pie. Can you provide more details for each of your issues?
