### ISSUE TITLE
Settings Activity crashes the application.

### ISSUE THREAD

**Issue by khalid-hussain** [khalid-hussain/HisnulMuslim#8]
This is due to the activity not having been properly implemented. Its skeleton has been added but the details are to be worked on. Options to be provided will be discussed once we get an empty Settings activity up and running.

**Comment by mdali92** [comment]
comment out line #48 in SettingsActivity.java

//setupActionBar();

This line sets up the Actionbar which is not needed for the settings activity.

The crashing should stop after this.

**Comment by ahmedre** [comment]
i just setup a theme for it which explicitly enables the window actionbar. we can also do some additional cleanup (ie remove the honeycomb+ checks) if we are indeed going to be api 14+.

**Comment by khalid-hussain** [comment]
Yes, I think a cleanup would be good. Jellybean and above seems like a good thing to do.
